name: Build and Deploy to Container Registry

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: "ubuntu-latest"

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "6.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build with dotnet
              run: dotnet build --configuration Release

            - name: Build and Push Image
              run: |
                  echo "${{ secrets.ACR_PASSWORD }}" | docker login -u "${{ secrets.ACR_USERNAME }}" --password-stdin microhack.azurecr.io &&
                  docker build -t microhack.azurecr.io/microhackapp:v1 -f Dockerfile . &&
                  docker push microhack.azurecr.io/microhackapp:v1

    deploy:
        name: Deploy Solution
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"

        steps:
            - name: Get Latest Container Image Tag
              id: get_tag
              run: |
                  TAG=$(az acr repository show-tags --name microhackregistry --repository microhackapp --orderby time_desc --output tsv --detail | head -n 1 | awk '{print $4}')
                  NUMERIC_TAG=$(echo "$TAG" | grep -oE '[0-9]+')
                  INCREMENTED_TAG=$((NUMERIC_TAG + 1))
                  UPDATED_TAG=$(echo "$TAG" | sed "s/$NUMERIC_TAG/$INCREMENTED_TAG/")
                  echo "::set-output name=image_tag::$UPDATED_TAG"
