name: Trigger auto deployment for microhack-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/microhack-containerapp-AutoDeployTrigger-c38ed946-eb00-4047-9e9b-284b31569801.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MICROHACKCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MICROHACKCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MICROHACKCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: microhack.azurecr.io
          registryUsername: ${{ secrets.MICROHACKCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MICROHACKCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: microhack-containerapp
          resourceGroup: MicroHack-AppServiceToContainerApp
          imageToBuild: microhack.azurecr.io/microhack-containerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


